-- MySQL Script generated by MySQL Workbench
-- Fri 27 Nov 2020 05:35:22 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema laptic
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `laptic` ;

-- -----------------------------------------------------
-- Schema laptic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laptic` ;
USE `laptic` ;

-- -----------------------------------------------------
-- Table `laptic`.`workouts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laptic`.`workouts` ;

CREATE TABLE IF NOT EXISTS `laptic`.`workouts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `bloc` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laptic`.`series`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laptic`.`series` ;

CREATE TABLE IF NOT EXISTS `laptic`.`series` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workoutId` INT NOT NULL,
  `exercice` VARCHAR(45) NOT NULL,
  `rest` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_series_1_idx` (`workoutId` ASC),
  CONSTRAINT `fk_series_workout1`
    FOREIGN KEY (`workoutId`)
    REFERENCES `laptic`.`workouts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laptic`.`repetitions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laptic`.`repetitions` ;

CREATE TABLE IF NOT EXISTS `laptic`.`repetitions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `serieId` INT NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `rest` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_repetitions_1_idx` (`serieId` ASC),
  CONSTRAINT `fk_repetitions_series1`
    FOREIGN KEY (`serieId`)
    REFERENCES `laptic`.`series` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
